targets:
  $default:
    sources:
      include:
        - lib/**.dart
        # required
        - pubspec.*
        ## synthetic files
        - $package$
        - lib/$lib$
    builders:
      auto_route_generator:auto_route_generator:
        # configs for @RoutePage() generator...
        options:
          enable_cached_builds: true
        generate_for:
          - lib/features/**/*_page.dart
      auto_route_generator:auto_router_generator:
        # configs for @AutoRouterConfig() generator...
        options:
          enable_cached_builds: true
        generate_for:
          - lib/app/app_router.dart
      freezed:freezed:
        generate_for:
          - lib/utils/client.dart
      riverpod_generator:riverpod_generator:
        generate_for:
          - lib/utils/api.dart
          - lib/utils/client.dart
          - lib/utils/secrets.dart
          - lib/utils/config/flavor.dart
      flutter_gen_runner:flutter_gen_runner:
        generate_for:
          - pubspec.yaml
