targets:
  $default:
    sources:
      include:
        - lib/**.dart
        # required
        - pubspec.*
        ## synthetic files
        - $package$
        - lib/$lib$
    builders:
      auto_route_generator:
        # configs for the @RoutePage() generator
        options:
          enable_cached_builds: true
        generate_for:
          - lib/features/*/presentation/*/*_page.dart
      auto_route_generator:auto_router_generator:
        # configs for the @AutoRouterConfig() generator
        options:
          enable_cached_builds: true
        generate_for:
          - lib/app/app_router.dart
      auto_route_generator:auto_router_module_generator:
        enabled: false
      freezed:
        # configs for the @freezed generator
        generate_for:
          - lib/utils/*.dart
          - lib/features/*/domain/*_entity.dart
          - lib/features/*/domain/*_model.dart
      json_serializable:
        # configs for the @JsonSerializable generator
        generate_for:
          - lib/features/*/domain/*_entity.dart
          - lib/features/*/domain/*_model.dart
        options:
          checked: true
      riverpod_generator:
        # configs for the @riverpod generator
        generate_for:
          - lib/utils/*.dart
          - lib/features/*/data/*_repository.dart
          - lib/features/*/application/*_service.dart
      flutter_gen_runner:
        # configs for the flutter.assets generator
        options:
          output: lib/gen/
        generate_for:
          - $package$
      build_version:
        # configs for the packageVersion generator...
        options:
          output: lib/gen/version.gen.dart
      envied_generator:envied:
        # configs for the @Envied generator
        generate_for:
          - lib/env/env.dart
        options:
          output: lib/gen/env.g.dart
