targets:
  $default:
    sources:
      include:
        - lib/**.dart
        # required
        - pubspec.*
        ## synthetic files
        - $package$
        - lib/$lib$
    builders:
      auto_route_generator:
        # configs for the @RoutePage() generator
        options:
          enable_cached_builds: true
        generate_for:
          - lib/features/*/presentation/**_page.dart
      auto_route_generator:auto_router_generator:
        # configs for the @AutoRouterConfig() generator
        options:
          enable_cached_builds: true
        generate_for:
          - lib/app/app_router.dart
      auto_route_generator:auto_router_module_generator:
        enabled: false
      freezed:
        # configs for the @freezed generator
        generate_for:
          - lib/utils/**.dart
          - lib/features/*/domain/**_model.dart
      riverpod_generator:
        # configs for the @riverpod generator
        generate_for:
          - lib/utils/**.dart
          - lib/features/*/data/**_data.dart
          - lib/features/*/domain/**_domain.dart
          - lib/features/*/presentation/**_controller.dart
      flutter_gen_runner:
        # configs for the flutter.assets generator
        generate_for:
          - $package$
      source_gen:combining_builder:
        # configs for the source_gen:combining_builder generator
        generate_for:
          - lib/**.dart
      json_serializable:
        # configs for the @JsonSerializable generator
        generate_for:
          - lib/features/*/domain/**_model.dart
      widgetbook_generator:app_builder:
        # configs for @App() generator...
        generate_for:
          - lib/widgetbook.generator.dart
      widgetbook_generator:use_case_builder:
        # configs for @UseCase() generator...
        generate_for:
          - lib/widgetbook.generator.dart
