targets:
  $default:
    sources:
      include:
        - lib/**.dart
        # required
        - pubspec.*
        ## synthetic files
        - $package$
        - lib/$lib$
    builders:
      auto_route_generator:
        # configs for the @RoutePage() generator
        options:
          enable_cached_builds: true
        generate_for:
          - lib/features/*/presentation/*/*_page.dart
      auto_route_generator:auto_router_generator:
        # configs for the @AutoRouterConfig() generator
        options:
          enable_cached_builds: true
        generate_for:
          - lib/app/app_router.dart
      auto_route_generator:auto_router_module_generator:
        enabled: false
      freezed:
        # configs for the @freezed generator
        generate_for:
          - lib/utils/*.dart
          - lib/features/*/domain/*_model.dart
          - lib/features/*/domain/*_entity.dart
        options:
          map: false
          when: false
      riverpod_generator:
        # configs for the @riverpod generator
        generate_for:
          - lib/utils/*.dart
          - lib/features/*/data/*_repository.dart
          - lib/features/*/application/*_service.dart
      flutter_gen_runner:
        # configs for the flutter.assets generator
        generate_for:
          - $package$
      source_gen:combining_builder:
        # configs for the source_gen:combining_builder generator
        generate_for:
          - lib/**.dart
      json_serializable:
        # configs for the @JsonSerializable generator
        generate_for:
          - lib/features/*/domain/*_model.dart
          - lib/features/*/domain/*_entity.dart
      build_version:build_version:
        # configs for the packageVersion generator...
        options:
          output: lib/gen/version.gen.dart
