arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
synthetic-package: false
output-class: AppLocalizations
output-dir: lib/l10n
untranslated-messages-file: untranslated.json
header: |
  /// All localized files.
  ///
  /// {@category Translations}
