collections = [] # only needed for DecapCMS
media_folder = "" # unneeded, but required by the schema


[build]
# The relative path to the directory to be published
publish = "build/web"

# Our Flutter Web build command
command = """
  if cd flutter; \
    then git pull && cd ..; \
    else git clone https://github.com/flutter/flutter.git; \
  fi \
  && flutter/bin/flutter config --enable-web \
  && flutter/bin/flutter pub get \
  && flutter/bin/flutter gen-l10n \
  && flutter/bin/cache/dart-sdk/bin/dart run build_runner build \
  && flutter/bin/cache/dart-sdk/bin/dart run dart_define generate \
  && flutter/bin/flutter build web --release --dart-define-from-file=dart_define.json
  """


# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
from = "/*"
status = 200
to = "/index.html"


[backend]
