collections = []  # only needed for CMS
media_folder = "" # unneeded, but required by the schema

[build]
# The relative path to the directory to be published
publish = "build/web"

# Our Flutter Web build command
command = "if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web"


[backend]
