blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/PSDTools/app/discussions
    about: Please ask and answer questions here. Also, feature requests go here.
